spring:
      datasource:
                url: jdbc:mysql://192.168.63.100:3306/eagle_eye_local?useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=500&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: root
my:
  name: default
example:
  property: default