spring:
      datasource:
                url: jdbc:mysql://192.168.63.100:3306/test?useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=500&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: "{cipher}67046de65af718f0aa466c3b6ee512cd1cfad8120ef5cbb33a628a2d001e5a13"
my:
  name: default
example:
  property: default
